import os
import glob
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import pairwise_distances

DATASET_ROOT = os.path.join("dataset", "python")

def load_comprehensive_dataset():
    records = []
    json_files = glob.glob(os.path.join(DATASET_ROOT, "*.json"))
    
    if not json_files:
        print(f"No JSON files found in '{DATASET_ROOT}'.")
        return pd.DataFrame()
        
    for jf in json_files:
        py_path = jf.replace(".json", ".py")
        if not os.path.exists(py_path):
            continue
            
        with open(jf, "r", encoding="utf-8") as f:
            meta = json.load(f)
            
        with open(py_path, "r", encoding="utf-8") as f:
            meta["raw_code_text"] = f.read()
            
        records.append(meta)
        
    return pd.DataFrame(records)

def main():
    df = load_comprehensive_dataset()
    if df.empty:
        return

    print("Extracting Structural and Semantic metrics...")

    # ==========================================
    # 1. PREPARE STRUCTURAL DATA (Melted for Panel A)
    # ==========================================
    metric_mapping = {
        "logical_loc": "Lines of Code",
        "ast_nodes": "AST Nodes",
        "cfg_nodes": "CFG Nodes",
        "cyclomatic_complexity": "Complexity",
        "function_count": "Functions",
        "loop_count": "Loops"
    }
    
    # Normalize metrics to a 0.0 - 1.0 scale
    scaler = MinMaxScaler()
    df_scaled = pd.DataFrame(scaler.fit_transform(df[list(metric_mapping.keys())]), columns=list(metric_mapping.values()))
    df_scaled["category"] = df["category"]
    df_scaled["label"] = df["label"]
    
    # Melt the dataframe so we can plot multiple distributions side-by-side
    df_melt = df_scaled.melt(id_vars=["category", "label"], var_name="Metric", value_name="Normalized Value")

    # ==========================================
    # 2. PREPARE SEMANTIC DATA (Uniqueness Score)
    # ==========================================
    tfidf = TfidfVectorizer(token_pattern=r"(?u)\b\w+\b|[=+\-*/<>:!]+", ngram_range=(1, 2))
    text_matrix = tfidf.fit_transform(df["raw_code_text"])
    
    # Compute full pairwise distance matrix
    dist_matrix = pairwise_distances(text_matrix, metric="cosine")
    
    # For each program, find its average distance to ALL OTHER programs
    uniqueness_scores = []
    for i in range(len(df)):
        distances_to_others = np.delete(dist_matrix[i], i)
        uniqueness_scores.append(np.mean(distances_to_others))
        
    df["semantic_uniqueness"] = uniqueness_scores

    # ==========================================
    # 3. PLOTTING THE ELEGANT 2-PANEL FIGURE
    # ==========================================
    print("Generating statistical variety analysis...")
    
    plt.rcParams.update({
        "font.family": "serif",
        "axes.labelsize": 11,
        "axes.titlesize": 13,
        "figure.dpi": 300,
        "axes.grid": True,
        "grid.alpha": 0.3,
        "grid.linestyle": "--"
    })

    fig, axes = plt.subplots(2, 1, figsize=(12, 11), gridspec_kw={'height_ratios': [1.1, 1]})
    fig.subplots_adjust(hspace=0.35)

    categories = df["category"].unique()
    palette = sns.color_palette("pastel", len(categories))
    
    # --- PANEL A: Structural Dispersion (Density Silhouette + Strip Overlay) ---
    ax1 = axes[0]
    
    # 1. The Silhouette: A subtle white violin showing the overall dataset density
    sns.violinplot(
        data=df_melt, x="Metric", y="Normalized Value", 
        color="#F8F9FA", inner=None, linewidth=1.5, ax=ax1, zorder=1
    )
    
    # 2. The Data: Scatter the actual programs across the silhouette
    sns.stripplot(
        data=df_melt, x="Metric", y="Normalized Value", hue="category",
        palette=palette, dodge=True, alpha=0.7, size=4, jitter=0.25, ax=ax1, zorder=2
    )

    # Formatting Panel A
    ax1.set_title("(A) Structural Dispersion: Code Complexity & Scale Variations", loc="left")
    ax1.set_xlabel("")
    ax1.set_ylabel("Normalized Metric Scale (0 to 1)")
    
    # Clean up the legend (remove duplicates generated by stripplot)
    handles, labels = ax1.get_legend_handles_labels()
    clean_labels = [l.replace("_", " ").title() for l in categories]
    ax1.legend(handles[:len(categories)], clean_labels, title="Category", 
               loc="upper right", bbox_to_anchor=(1.2, 1), frameon=False)
    
    sns.despine(ax=ax1, top=True, right=True)

    # --- PANEL B: Semantic Uniqueness (Violin + Swarm Distribution) ---
    ax2 = axes[1]
    
    sns.violinplot(
        data=df, 
        x="category", 
        y="semantic_uniqueness", 
        hue="label",
        split=True,            
        inner="quart",         
        palette="muted", 
        linewidth=1,
        alpha=0.7,
        ax=ax2
    )

    # Formatting Panel B
    ax2.set_title("(B) Semantic Uniqueness: Average Textual Distance to All Other Programs", loc="left")
    ax2.set_xlabel("")
    ax2.set_ylabel("Cosine Distance")
    
    # --- ZOOMED Y-AXIS (0.8 to 1.0) ---
    ax2.set_ylim(0.85, 1.0)
    
    clean_cats = [c.replace("_", " ").title() for c in categories]
    ax2.set_xticklabels(clean_cats)
    ax2.legend(title="Execution Mode", loc="upper right", bbox_to_anchor=(1.2, 1), frameon=False)
    sns.despine(ax=ax2, top=True, right=True)

    # Export
    output_file = "dataset_structural_semantic_variety.png"
    plt.savefig(output_file, bbox_inches="tight", dpi=300)
    print(f"✅ Scientific composite saved to: {output_file}")

if __name__ == "__main__":
    main()